### ISSUE TITLE
add more than one feature for command twgit demo merge-feature

### ISSUE THREAD

**Issue by chemidy** [Twenga/twgit#121]
It will be very usefull to add more than one feature on twgit demo merge-feature

for example  : 
twgit demo merge-feature 007 008 009 1728 4569 118218

**Comment by Sebastien-Hanicotte** [comment]
It could be usefull when dealing with demo of multiple feature... and such "evolution" would be also interesting for the twgit release merge-into-feature.

But I see some difficulties with such a feature.

What if your 007 and 008 feature raise a merge error ?
Then merging with a third feature raise a new merge error ?

Merging one feature at a time allows the user to deal with the merge functionnality step by step and because it could be difficult with an "easy" merge, dealing with multiple "merge" could really 'give someone a headache' (sorry for the picture :astonished:)
