### ISSUE TITLE
add % Done on redmine subject

### ISSUE THREAD

**Issue by chemidy** [Twenga/twgit#123]
It will be cool to have % done of a feature on redmine subject feature !!!

**Comment by rderocle** [comment]
you want to retrieve the % done from redmine and display this info next to the retrieved feature's name in twgit ?

**Comment by Sebastien-Hanicotte** [comment]
Problem with such a feature is that disable the use of the .twgit_feature_subject caching file.

This cache was certainly proposed to limit the call to the Redmine API.

By the way, I'm not a big fan of the percentage in Redmine, I usually put 0% when not assigned, 50% when in progress and 100% when done... not so often a more precise information because it will too often be stuck at 98%, waiting for some review, aso ;)

**Comment by ltoussaint** [comment]
Maybe we could add an option to specify if we want to get progress.
If yes, we need to remove cache system for this case.
