### ISSUE TITLE
Alert on hotfix start or release start when current user is different from creator

### ISSUE THREAD

**Issue by geoffroy-aubry** [Twenga/twgit#85]
so current user will know that he isn't alone on this hotfix or release…

**Comment by Sebastien-Hanicotte** [comment]
Hi Chemidy, I was wondering how far was the development on this feature ?

I ask that because I just encounter the same problem, one of my partner opened the hotfix, was working in it.
Then, I asked twgit to open a hotfix, made my fix, commit and closed the hotfix without knowing another has opened it.

We should for sure had on the opening and assurely when closing the hotfix an alert saying that we we're not the user who opened it and wondering if we really want the hotfix closed.

By the way, if we are the owner the hotfix and somebody else has worked on the hotfix, when closing it, we should also have a message explaining that other worked or are working in the hotfix and wondering if we can close it.
